"""Phase 1A ingestion-mode decision for a generic upstream evidence contract."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from pipeline.adapter.upstream_gates import (
    QueryRunner,
    get_signal_availability,
    get_token_allowlist_status,
    get_upstream_validation_summary,
)
from pipeline.adapter.upstream_health_client import ServiceHealth, UpstreamHealthError
from pipeline.adapter.upstream_schema_inspector import validate_schema_and_identity


@dataclass(frozen=True)
class Phase1ADecision:
    ingestion_mode: str
    upstream_contract_passed: bool
    x402_signal_source_available: bool
    missing_fields: list[str]
    target_tables: list[str]
    upstream_match_rate: float | None
    upstream_last_validated_at: str | None
    upstream_validation_status: str
    token_symbol_check_passed: bool
    decision_notes: str

    def to_json_dict(self) -> dict[str, Any]:
        return asdict(self)


def decide_ingestion_mode(
    health: ServiceHealth,
    run_query: QueryRunner,
    chain: str = "solana",
    token_symbol: str = "PYUSD",
) -> Phase1ADecision:
    if health.status == "unavailable":
        raise UpstreamHealthError("upstream health is unavailable")

    signal = get_signal_availability(run_query)
    token_allowed = get_token_allowlist_status(run_query, chain, token_symbol)
    schema = validate_schema_and_identity(run_query, chain, token_symbol)
    validation = get_upstream_validation_summary(run_query, chain, token_symbol)

    contract_passed = schema.passed and token_allowed
    if not contract_passed:
        ingestion_mode = "pivot"
        notes = "Upstream evidence contract failed schema or token allowlist checks."
    elif (
        signal.x402_signal_source_available
        and signal.memo_field_available
        and signal.program_id_available
        and signal.raw_instruction_ref_available
    ):
        ingestion_mode = "adapter_plus_signal_fetch"
        notes = "Signal-aware upstream evidence contract detected."
    else:
        ingestion_mode = "adapter"
        notes = "Generic upstream adapter selected; x402 semantic signal unavailable, so benchmark fallback is required."

    if health.status == "degraded" and ingestion_mode != "pivot":
        notes = f"{notes} Upstream health is degraded; block validated/public-fresh claims."

    return Phase1ADecision(
        ingestion_mode=ingestion_mode,
        upstream_contract_passed=contract_passed,
        x402_signal_source_available=signal.x402_signal_source_available,
        missing_fields=schema.missing_fields,
        target_tables=schema.target_tables,
        upstream_match_rate=validation.upstream_match_rate,
        upstream_last_validated_at=validation.upstream_last_validated_at,
        upstream_validation_status=validation.upstream_validation_status,
        token_symbol_check_passed=token_allowed and schema.token_symbol_check_passed,
        decision_notes=notes,
    )


def write_decision_artifacts(
    decision: Phase1ADecision,
    health: ServiceHealth,
    config_path: Path = Path("config/ingestion_mode.json"),
    doc_path: Path = Path("docs/upstream-evidence-contract.md"),
) -> None:
    config_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.parent.mkdir(parents=True, exist_ok=True)

    config_path.write_text(json.dumps(decision.to_json_dict(), indent=2) + "\n", encoding="utf-8")
    doc_path.write_text(_render_contract_doc(decision, health), encoding="utf-8")


def _render_contract_doc(decision: Phase1ADecision, health: ServiceHealth) -> str:
    return f"""# Upstream Evidence Contract

Generated by: `@codex`

## Health Contract

- contract_version: `{health.contract_version}`
- status: `{health.status}`
- suitable_for_runtime_routing: `{str(health.suitable_for_runtime_routing).lower()}`

## Decision

- ingestion_mode: `{decision.ingestion_mode}`
- upstream_contract_passed: `{str(decision.upstream_contract_passed).lower()}`
- x402_signal_source_available: `{str(decision.x402_signal_source_available).lower()}`
- upstream_validation_status: `{decision.upstream_validation_status}`
- upstream_match_rate: `{decision.upstream_match_rate}`
- upstream_last_validated_at: `{decision.upstream_last_validated_at}`
- token_symbol_check_passed: `{str(decision.token_symbol_check_passed).lower()}`

## Inspected Contract Objects

{chr(10).join(f"- `{table}`" for table in decision.target_tables)}

## Missing Fields

{chr(10).join(f"- `{field}`" for field in decision.missing_fields) if decision.missing_fields else "- none"}

## Notes

{decision.decision_notes}
"""
